// packages/vue/lib/Giscus.tsx
import {
  defineComponent,
  PropType,
  onMounted,
  ref,
  onUnmounted,
  computed
} from 'vue'
import type { LegacyRef } from 'react'
import { GiscusProps } from '@shared/types'
import {
  addDefaultStyles,
  createErrorMessageListener,
  formatError,
  getIframeSrc,
  GISCUS_ORIGIN,
  GISCUS_SESSION_KEY
} from '@shared/util'
import iFrameResizer from 'iframe-resizer'

const Giscus = defineComponent({
  props: {
    repo: {
      type: String as PropType<GiscusProps['repo']>,
      required: true
    },
    repoId: {
      type: String as PropType<GiscusProps['repoId']>,
      required: true
    },
    category: String as PropType<GiscusProps['category']>,
    categoryId: String as PropType<GiscusProps['categoryId']>,
    mapping: {
      type: String as PropType<GiscusProps['mapping']>,
      required: true
    },
    term: String as PropType<GiscusProps['term']>,
    lang: {
      type: String as PropType<GiscusProps['lang']>,
      default: 'en'
    },
    theme: {
      type: String as PropType<GiscusProps['theme']>,
      default: 'light'
    },
    reactionsEnabled: {
      type: String as PropType<GiscusProps['reactionsEnabled']>,
      default: '1'
    },
    emitMetadata: {
      type: String as PropType<GiscusProps['emitMetadata']>,
      default: '0'
    },
    inputPosition: {
      type: String as PropType<GiscusProps['inputPosition']>,
      default: 'bottom'
    }
  },

  setup(props: GiscusProps) {
    const session = ref('')
    const src = computed(() =>
      getIframeSrc({ ...props, session: session.value })
    )

    onMounted(() => {
      const origin = location.href
      const url = new URL(origin)
      const savedSession = localStorage.getItem(GISCUS_SESSION_KEY)
      session.value = url.searchParams.get('giscus') || ''

      if (session.value) {
        localStorage.setItem(GISCUS_SESSION_KEY, JSON.stringify(session.value))
        url.searchParams.delete('giscus')
        history.replaceState(undefined, document.title, url.toString())
      } else if (savedSession) {
        try {
          session.value = JSON.parse(savedSession || '') || ''
        } catch (e: any) {
          session.value = ''
          localStorage.removeItem(GISCUS_SESSION_KEY)
          console.warn(`${formatError(e?.message)} Session has been cleared.`)
        }
      }
    })

    onMounted(addDefaultStyles)

    const listener = createErrorMessageListener(() => (session.value = ''))
    onMounted(() => window.addEventListener('message', listener))
    onUnmounted(() => window.removeEventListener('message', listener))

    const iframe = ref<
      HTMLIFrameElement | { iFrameResizer: { removeListeners: () => void } }
    >()

    onMounted(() => {
      if (!iframe.value) return
      iframe.value = iframe.value as HTMLIFrameElement
      iframe.value.addEventListener('load', () =>
        iFrameResizer.iframeResizer(
          { checkOrigin: [GISCUS_ORIGIN] },
          iframe.value as HTMLIFrameElement
        )
      )
    })

    onUnmounted(() => {
      if (iframe.value && 'iFrameResizer' in iframe.value)
        iframe.value?.iFrameResizer?.removeListeners()
    })

    return () => (
      <div className="giscus">
        <iframe
          title="Comments"
          className="giscus-frame"
          src={src.value}
          ref={iframe as any as LegacyRef<HTMLIFrameElement>}
        />
      </div>
    )
  }
})

export default Giscus

// packages/svelte/lib/Giscus.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte'

  import {
    addDefaultStyles,
    createErrorMessageListener,
    formatError,
    getIframeSrc,
    GISCUS_ORIGIN,
    GISCUS_SESSION_KEY
  } from '../../@shared/util'
  import type { GiscusProps } from '../../@shared/types'
  import iFrameResizer from 'iframe-resizer'

  export let repo: GiscusProps['repo']
  export let repoId: GiscusProps['repoId']
  export let category: GiscusProps['category'] = ''
  export let categoryId: GiscusProps['categoryId'] = ''
  export let mapping: GiscusProps['mapping']
  export let term: GiscusProps['term'] = ''
  export let lang: GiscusProps['lang'] = 'en'
  export let theme: GiscusProps['theme'] = 'light'
  export let reactionsEnabled: GiscusProps['reactionsEnabled'] = '1'
  export let emitMetadata: GiscusProps['emitMetadata'] = '0'
  export let inputPosition: GiscusProps['inputPosition'] = 'bottom'

  let session = ''
  $: src = getIframeSrc({
    repo,
    repoId,
    category,
    categoryId,
    mapping,
    term,
    lang,
    theme,
    reactionsEnabled,
    emitMetadata,
    inputPosition,
    session,
  })

  onMount(() => {
    const origin = location.href
    const url = new URL(origin)
    const savedSession = localStorage.getItem(GISCUS_SESSION_KEY)
    session = url.searchParams.get('giscus') || ''

    if (session) {
      localStorage.setItem(GISCUS_SESSION_KEY, JSON.stringify(session))
      url.searchParams.delete('giscus')
      history.replaceState(undefined, document.title, url.toString())
    } else if (savedSession) {
      try {
        session = JSON.parse(savedSession || '') || ''
      } catch (e) {
        session = ''
        localStorage.removeItem(GISCUS_SESSION_KEY)
        console.warn(`${formatError(e?.message)} Session has been cleared.`)
      }
    }
  })

  onMount(addDefaultStyles)

  const listener = createErrorMessageListener(() => (session = ''))
  onMount(() => window.addEventListener('message', listener))
  onDestroy(() => window.removeEventListener('message', listener))

  let iframe:
    | HTMLIFrameElement
    | undefined
    | { iFrameResizer: { removeListeners: () => void } }

  onMount(() => {
    if (!iframe) return
    iframe = iframe as HTMLIFrameElement
    iframe.addEventListener('load', () =>
      iFrameResizer.iframeResizer(
        { checkOrigin: [GISCUS_ORIGIN] },
        iframe as HTMLIFrameElement
      )
    )
  })

  onDestroy(() => {
    if (iframe && 'iFrameResizer' in iframe)
      iframe?.iFrameResizer?.removeListeners()
  })
</script>

<div class="giscus">
  <iframe title="Comments" class="giscus-frame" src={src} bind:this={iframe} />
</div>
