// packages/react/lib/Utterances.tsx
import React, { FC, useRef, useEffect } from 'react'
import { UtterancesProps } from '@shared/types'
import { createScriptElement, putChildElement } from '@shared/util'

const Utterances: FC<UtterancesProps> = ({
  repo,
  label,
  theme,
  issueTerm,
  issueNumber
}) => {
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!ref.current) return

    const scriptEl = createScriptElement({
      repo,
      label,
      theme,
      issueTerm,
      issueNumber: issueNumber as never
    })

    putChildElement(ref.current, scriptEl)
  }, [])

  return <div ref={ref} />
}

export default Utterances

// packages/svelte/lib/Utterances.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { createScriptElement, putChildElement } from '../../@shared/util'
  import  type { Repo, Theme,  Issue } from '../../@shared/types'

  type $$Props = Issue

  export let repo: Repo
  export let theme: Theme
  export const label: string = undefined
  export let issue: Issue = (() => {
    return {
      issueTerm: $$props.issueTerm,
      issueNumber: $$props.issueNumber
    } as Issue
  })()


  let divRef: HTMLDivElement | undefined;
  onMount(() => {
    if(!divRef) return
    const scriptEl = createScriptElement({
      repo,
      theme,
      label,
      ...issue,
    })

    divRef = putChildElement(divRef, scriptEl)
  });
</script>

<div bind:this={divRef} />
