// react/src/lib/Giscus.tsx
import { useEffect, useState } from 'react';
import type { GiscusProps } from './types';

export default function Giscus({
  id,
  host,
  repo,
  repoId,
  category,
  categoryId,
  mapping,
  term,
  strict,
  reactionsEnabled,
  emitMetadata,
  inputPosition,
  theme,
  lang,
  loading,
}: GiscusProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    if (mounted) return;
    import('giscus').then(() => setMounted(true));
  }, []);

  if (!mounted) return null;

  return (
    <giscus-widget
      id={id}
      host={host}
      repo={repo}
      repoid={repoId}
      category={category}
      categoryid={categoryId}
      mapping={mapping}
      term={term}
      strict={strict}
      reactionsenabled={reactionsEnabled}
      emitmetadata={emitMetadata}
      inputposition={inputPosition}
      theme={theme}
      lang={lang}
      loading={loading}
    />
  );
}

// solid/src/lib/Giscus.tsx
import { createEffect, createSignal, Show } from 'solid-js';
import type { GiscusProps } from './types';

export default function Giscus(props: GiscusProps) {
  const [mounted, setMounted] = createSignal(false);

  createEffect(() => {
    if (mounted()) return;
    void import('giscus').then(() => setMounted(true));
  });

  // Note: make sure to use kebab-case for the web component's attributes,
  // as it seems Solid cannot properly handle the properties without it.

  return (
    <Show when={mounted()} fallback={null}>
      <giscus-widget
        id={props.id}
        host={props.host}
        repo={props.repo}
        repo-id={props.repoId}
        category={props.category}
        category-id={props.categoryId}
        mapping={props.mapping}
        term={props.term}
        strict={props.strict}
        reactions-enabled={props.reactionsEnabled}
        emit-metadata={props.emitMetadata}
        input-position={props.inputPosition}
        theme={props.theme}
        lang={props.lang}
        loading={props.loading}
      />
    </Show>
  );
}
