// packages/svelte/_debug/App.svelte
<script lang="ts">
  import Giscus from '../lib/Giscus.svelte'
</script>

<main>
  <Giscus
    repo="giscus/giscus-component"
    repoId="MDEwOlJlcG9zaXRvcnkzOTEzMTMwMjA="
    category="Announcements"
    categoryId="DIC_kwDOF1L2fM4B-hVS"
    mapping="specific"
    term="Welcome to giscus-component Discussions"
    reactionsEnabled="1"
    emitMetadata="0"
    inputPosition="bottom"
    theme="light"
    lang="en"
  />
</main>

// packages/vue/_debug/App.vue
<template>
  <Giscus
    repo="giscus/giscus-component"
    repoId="MDEwOlJlcG9zaXRvcnkzOTEzMTMwMjA="
    category="Announcements"
    categoryId="DIC_kwDOF1L2fM4B-hVS"
    mapping="specific"
    term="Welcome to giscus-component Discussions"
    reactionsEnabled="1"
    emitMetadata="0"
    inputPosition="bottom"
    theme="light"
    lang="en"
  />
</template>

<script setup lang="ts"></script>
