// svelte/src/lib/Giscus.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type {
    AvailableLanguage,
    BooleanString,
    InputPosition,
    Loading,
    Mapping,
    Theme,
  } from '.';

  onMount(() => import('giscus'));

  export let id: string = undefined;
  export let repo: `${string}/${string}`;
  export let repoId: string;
  export let category: string = undefined;
  export let categoryId: string = undefined;
  export let mapping: Mapping = 'pathname';
  export let term: string = undefined;
  export let reactionsEnabled: BooleanString = '1';
  export let emitMetadata: BooleanString = '0';
  export let inputPosition: InputPosition = 'bottom';
  export let theme: Theme = 'light';
  export let lang: AvailableLanguage = 'en';
  export let loading: Loading = 'eager';
</script>

<giscus-widget
  {id}
  {repo}
  repoid={repoId}
  {category}
  categoryid={categoryId}
  {mapping}
  {term}
  reactionsenabled={reactionsEnabled}
  emitmetadata={emitMetadata}
  inputposition={inputPosition}
  {theme}
  {lang}
  {loading}
/>

// vue/src/lib/Giscus.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import type { AvailableLanguage, BooleanString, InputPosition, Loading, Mapping, Repo, Theme } from '.';

defineProps<{
  id?: string;
  repo: Repo;
  repoId: string;
  category?: string;
  categoryId?: string;
  mapping: Mapping;
  term?: string;
  theme?: Theme;
  reactionsEnabled?: BooleanString;
  emitMetadata?: BooleanString;
  inputPosition?: InputPosition;
  lang?: AvailableLanguage;
  loading?: Loading;
}>();

onMounted(() => import('giscus'));
</script>

<template>
  <giscus-widget
    :id="id"
    :repo="repo"
    :repoid="repoId"
    :category="category"
    :categoryid="categoryId"
    :mapping="mapping"
    :term="term"
    :reactionsenabled="reactionsEnabled"
    :emitmetadata="emitMetadata"
    :inputposition="inputPosition"
    :theme="theme"
    :lang="lang"
    :loading="loading"
  />
</template>
