// vue/src/lib/Giscus.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import type {
  AvailableLanguage,
  BooleanString,
  InputPosition,
  Loading,
  Mapping,
  Repo,
  Theme,
} from './types';

defineProps<{
  id?: string;
  repo: Repo;
  repoId: string;
  category?: string;
  categoryId?: string;
  mapping: Mapping;
  term?: string;
  theme?: Theme;
  reactionsEnabled?: BooleanString;
  emitMetadata?: BooleanString;
  inputPosition?: InputPosition;
  lang?: AvailableLanguage;
  loading?: Loading;
}>();

onMounted(() => import('giscus'));
</script>

<template>
  <giscus-widget
    :id="id"
    :repo="repo"
    :repoid="repoId"
    :category="category"
    :categoryid="categoryId"
    :mapping="mapping"
    :term="term"
    :reactionsenabled="reactionsEnabled"
    :emitmetadata="emitMetadata"
    :inputposition="inputPosition"
    :theme="theme"
    :lang="lang"
    :loading="loading"
  />
</template>

// preact/src/lib/Giscus.tsx
import type { JSX } from 'preact';
import { useEffect } from 'preact/compat';
import type { GiscusProps } from './types';

export default function Giscus({
  id,
  repo,
  repoId,
  category,
  categoryId,
  mapping,
  term,
  reactionsEnabled,
  emitMetadata,
  inputPosition,
  theme,
  lang,
  loading,
}: GiscusProps): JSX.Element {
  useEffect(() => {
    import('giscus');
  }, []);

  const widget = (
    // @ts-expect-error
    <giscus-widget
      id={id}
      repo={repo}
      repoid={repoId}
      category={category}
      categoryid={categoryId}
      mapping={mapping}
      term={term}
      reactionsenabled={reactionsEnabled}
      emitmetadata={emitMetadata}
      inputposition={inputPosition}
      theme={theme}
      lang={lang}
      loading={loading}
    />
  );

  return widget;
}
